version: '3.4'

services:
  moodtrackingapplication:
    image: moodtrackingapplication
    build:
      context: .
      dockerfile: ./Dockerfile
    secrets:
      - cookies-password


secrets:
  cookies-password:
    external: true